const KEY="peroStoreUsers",SESSION="peroStoreSession";
const getUsers=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}};
const saveUsers=u=>localStorage.setItem(KEY,JSON.stringify(u));
const msg=(id,t,show=true)=>{const e=document.getElementById(id);if(e){e.textContent=t;e.style.display=show?"block":"none"}};

document.querySelectorAll(".eye").forEach(b=>b.addEventListener("click",()=>{const i=document.getElementById(b.dataset.target);if(i)i.type=i.type==="password"?"text":"password"}));
document.querySelectorAll(".switch-register").forEach(b=>b.addEventListener("click",()=>{document.querySelector(".login-view")?.classList.remove("active");document.querySelector(".register-view")?.classList.add("active")}));
document.querySelectorAll(".switch-login").forEach(b=>b.addEventListener("click",()=>{document.querySelector(".register-view")?.classList.remove("active");document.querySelector(".login-view")?.classList.add("active")}));

document.getElementById("registerForm")?.addEventListener("submit",e=>{e.preventDefault();msg("registerError","",false);msg("success","",false);const username=document.getElementById("username").value.trim(),email=document.getElementById("email").value.trim().toLowerCase(),password=document.getElementById("regPassword").value,confirm=document.getElementById("confirmPassword").value,list=getUsers();if(username.length<3)return msg("registerError","Username minimal 3 karakter.");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return msg("registerError","Email tidak valid.");if(password.length<6)return msg("registerError","Password minimal 6 karakter.");if(password!==confirm)return msg("registerError","Password tidak sama.");if(list.some(u=>u.username.toLowerCase()===username.toLowerCase()))return msg("registerError","Username sudah digunakan.");if(list.some(u=>u.email===email))return msg("registerError","Email sudah terdaftar.");list.push({id:String(Date.now()),username,email,password});saveUsers(list);msg("success","Akun berhasil dibuat. Silakan login.");setTimeout(()=>{document.querySelector(".register-view")?.classList.remove("active");document.querySelector(".login-view")?.classList.add("active");document.getElementById("identity").value=username},900)});

document.getElementById("loginForm")?.addEventListener("submit",e=>{e.preventDefault();msg("loginError","",false);const id=document.getElementById("identity").value.trim().toLowerCase(),pass=document.getElementById("password").value,u=getUsers().find(x=>x.username.toLowerCase()===id||x.email===id);if(!u)return msg("loginError","Username atau email tidak ditemukan.");if(u.password!==pass)return msg("loginError","Password salah.");const s=JSON.stringify({id:u.id,username:u.username,email:u.email});(document.getElementById("remember").checked?localStorage:sessionStorage).setItem(SESSION,s);location.href="store.html"});

document.getElementById("forgot")?.addEventListener("click",e=>{e.preventDefault();alert("Reset password membutuhkan backend.")});
document.getElementById("google")?.addEventListener("click",()=>alert("Google Login membutuhkan OAuth/backend."));
